// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VacinaCao.API.Data;

#nullable disable

namespace VacinaCao.API.Migrations
{
    [DbContext(typeof(VacinaCaoContext))]
    [Migration("20231013185341_InitialMigrations")]
    partial class InitialMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("VacinaCao.API.Models.Pacientes", b =>
                {
                    b.Property<Guid>("PacId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data_Nascimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Especie")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PacId");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("VacinaCao.API.Models.Tutores", b =>
                {
                    b.Property<Guid>("TutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Createtime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<Guid>("PacId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TutorId");

                    b.ToTable("Tutores");
                });

            modelBuilder.Entity("VacinaCao.API.Models.VacEstoque", b =>
                {
                    b.Property<Guid>("VaciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data_Fabricacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data_Validade")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Lote")
                        .HasColumnType("int");

                    b.Property<string>("Nome_Vacina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Refrigeracao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VaciId");

                    b.ToTable("Estoque_Vacina");
                });

            modelBuilder.Entity("VacinaCao.API.Models.Vacinacao", b =>
                {
                    b.Property<Guid>("Id_Vacinacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data_Aplicacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PacId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reacoes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VaciId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id_Vacinacao");

                    b.ToTable("Vacinacao");
                });
#pragma warning restore 612, 618
        }
    }
}
